# 
# Sistemas de Gestão de Dados 2024/2025
# Trabalho Prático
#
# Authors: 
#   Diana Martins <dianamartins@student.dei.uc.pt>
#   University of Coimbra
version: '3'

services:
  db:
    build: ./postgresql
    container_name: db_deijet
    expose:
      - "5432"
    ports:
      - "5433:5432"
  api:
    build: ./python
    container_name: deijet_api
    volumes:
      - "./python/app:/app"
    expose:
      - "5000"
    ports:
      - "8080:5000"
    depends_on:
      - db