# 
# Sistema de Gestão de Dados 2024/2025
# Trabalho Prático
#

from python:3.13.0-alpine3.20

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install --no-cache-dir --upgrade pip

run pip install flask

run pip install jwt

run pip install python-dotenv

run pip install psycopg2-binary

run pip install psycopg2

copy . /app

volume ["/app"]

workdir /app

run mkdir -p logs

EXPOSE 5000

CMD ["python", "deijet-api.py"]